name: Tag Monthly Commit
on:
  schedule:
    - cron: '0 0 1 * *' # Runs at midnight on the first day of every month

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Tag
        run: |
          # Get the current month and year
          current_month_year=$(date +"%Y-%m")
          # Tag the current commit with the current month and year
          git config --global user.email "46966993+maixnor@users.noreply.github.com"
          git config --global user.name "Benjamin Meixner"
          git tag -a $current_month_year -m "Monthly tag for $current_month_year"

          # Push the tag
          git push --tags

